using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using PluginHub;
using PluginHub.Module;
using UnityEditor;
using UnityEngine;

namespace PluginHub.Module
{
    //展示出所有unity内置的icon，编写插件的时候可以查找合适的直接使用
    public class BuildInIconGalleryModule : PluginHubModuleBase
    {
        public override string moduleName
        {
            get { return "内置图标库"; }
        }

        //Unity所有内置icon的名称字符串  来源：https://unitylist.com/p/5c3/Unity-editor-icons
        //或者这里： https://github.com/halak/unity-editor-icons
        //某些icon由于unity版本原因不存在，旧版unity会有更多缺少的icon
        private static string[] iconNames = new String[]
        {
            "aboutwindow.mainheader", "Add-Available", "Add-Available@2x", "ageialogo", "AimConstraint Icon",
            "alertDialog", "alertDialog@2x", "align_horizontally", "align_horizontally_center",
            "align_horizontally_center_active", "align_horizontally_left", "align_horizontally_left_active",
            "align_horizontally_right", "align_horizontally_right_active", "align_vertically",
            "align_vertically_bottom", "align_vertically_bottom_active", "align_vertically_center",
            "align_vertically_center_active", "align_vertically_top", "align_vertically_top_active",
            "AlphabeticalSorting", "AlphabeticalSorting@2x", "AnalyticsTracker Icon", "Animation Icon",
            "Animation.AddEvent", "Animation.AddKeyframe", "Animation.EventMarker", "Animation.FilterBySelection",
            "Animation.FirstKey", "Animation.LastKey", "Animation.NextKey", "Animation.Play", "Animation.PrevKey",
            "Animation.Record", "Animation.Record@2x", "Animation.SequencerLink", "animationanimated",
            "AnimationClip Icon", "AnimationClip On Icon", "animationdopesheetkeyframe", "animationkeyframe",
            "animationnocurve", "animationvisibilitytoggleoff", "animationvisibilitytoggleoff@2x",
            "animationvisibilitytoggleon", "animationvisibilitytoggleon@2x", "AnimationWindowEvent Icon",
            "AnimationWrapModeMenu", "Animator Icon", "AnimatorController Icon", "AnimatorController On Icon",
            "AnimatorOverrideController Icon", "AnimatorOverrideController On Icon", "AnimatorState Icon",
            "AnimatorStateMachine Icon", "AnimatorStateTransition Icon", "AnyStateNode Icon", "AreaEffector2D Icon",
            "AreaLight Gizmo", "AreaLight Icon", "AspectRatioFitter Icon", "Assembly Icon",
            "AssemblyDefinitionAsset Icon", "AssemblyDefinitionReferenceAsset Icon", "AssemblyLock", "Asset Store",
            "Asset Store@2x", "AssetStore Icon", "Audio Mixer", "Audio Mixer@2x", "AudioChorusFilter Icon",
            "AudioClip Icon", "AudioClip On Icon", "AudioDistortionFilter Icon", "AudioEchoFilter Icon",
            "AudioHighPassFilter Icon", "AudioImporter Icon", "AudioListener Icon", "AudioLowPassFilter Icon",
            "AudioMixerController Icon", "AudioMixerController On Icon", "AudioMixerGroup Icon",
            "AudioMixerSnapshot Icon", "AudioMixerView Icon", "AudioReverbFilter Icon", "AudioReverbZone Icon",
            "AudioSource Gizmo", "AudioSource Icon", "AudioSpatializerMicrosoft Icon", "AutoLightbakingOff",
            "AutoLightbakingOff@2x", "AutoLightbakingOn", "AutoLightbakingOn@2x", "Avatar Icon", "AvatarCompass",
            "AvatarController.Layer", "AvatarController.LayerHover", "AvatarController.LayerSelected",
            "AvatarMask Icon", "AvatarMask On Icon", "AvatarPivot", "AvatarPivot@2x", "AvatarSelector",
            "AvatarSelector@2x", "back", "back@2x", "beginButton-On", "beginButton", "BillboardAsset Icon",
            "BillboardRenderer Icon", "blendKey", "blendKeyOverlay", "blendKeySelected", "blendSampler",
            "BlendTree Icon", "blueGroove", "BodyPartPicker", "BodySilhouette", "boo Script Icon", "BoxCollider Icon",
            "BoxCollider2D Icon", "BuildSettings.Android On", "BuildSettings.Android On@2x", "BuildSettings.Android",
            "BuildSettings.Android.Small", "BuildSettings.Android.Small@2x", "BuildSettings.Android@2x",
            "BuildSettings.Broadcom", "BuildSettings.Editor", "BuildSettings.Editor.Small", "BuildSettings.Facebook On",
            "BuildSettings.Facebook On@2x", "BuildSettings.Facebook", "BuildSettings.Facebook.Small",
            "BuildSettings.Facebook.Small@2x", "BuildSettings.Facebook@2x", "BuildSettings.FlashPlayer",
            "BuildSettings.FlashPlayer.Small", "BuildSettings.iPhone On", "BuildSettings.iPhone On@2x",
            "BuildSettings.iPhone", "BuildSettings.iPhone.Small", "BuildSettings.iPhone.Small@2x",
            "BuildSettings.iPhone@2x", "BuildSettings.Lumin On", "BuildSettings.Lumin On@2x", "BuildSettings.Lumin",
            "BuildSettings.Lumin.small", "BuildSettings.Lumin.small@2x", "BuildSettings.Lumin@2x",
            "BuildSettings.Metro On", "BuildSettings.Metro On@2x", "BuildSettings.Metro", "BuildSettings.Metro.Small",
            "BuildSettings.Metro.Small@2x", "BuildSettings.Metro@2x", "BuildSettings.N3DS On",
            "BuildSettings.N3DS On@2x", "BuildSettings.N3DS", "BuildSettings.N3DS.Small", "BuildSettings.N3DS.Small@2x",
            "BuildSettings.N3DS@2x", "BuildSettings.PS4 On", "BuildSettings.PS4 On@2x", "BuildSettings.PS4",
            "BuildSettings.PS4.Small", "BuildSettings.PS4.Small@2x", "BuildSettings.PS4@2x", "BuildSettings.PSM",
            "BuildSettings.PSM.Small", "BuildSettings.PSP2", "BuildSettings.PSP2.Small", "BuildSettings.SelectedIcon",
            "BuildSettings.Stadia On", "BuildSettings.Stadia On@2x", "BuildSettings.Stadia",
            "BuildSettings.Stadia.small", "BuildSettings.Stadia.Small@2x", "BuildSettings.Stadia@2x",
            "BuildSettings.Standalone On", "BuildSettings.Standalone On@2x", "BuildSettings.Standalone",
            "BuildSettings.Standalone.Small", "BuildSettings.Standalone.Small@2x", "BuildSettings.Standalone@2x",
            "BuildSettings.StandaloneBroadcom.Small", "BuildSettings.StandaloneGLES20Emu.Small",
            "BuildSettings.StandaloneGLESEmu", "BuildSettings.StandaloneGLESEmu.Small", "BuildSettings.Switch On",
            "BuildSettings.Switch On@2x", "BuildSettings.Switch", "BuildSettings.Switch.Small",
            "BuildSettings.Switch.Small@2x", "BuildSettings.Switch@2x", "BuildSettings.tvOS On",
            "BuildSettings.tvOS On@2x", "BuildSettings.tvOS", "BuildSettings.tvOS.Small", "BuildSettings.tvOS.Small@2x",
            "BuildSettings.tvOS@2x", "BuildSettings.Web", "BuildSettings.Web.Small", "BuildSettings.WebGL On",
            "BuildSettings.WebGL On@2x", "BuildSettings.WebGL", "BuildSettings.WebGL.Small",
            "BuildSettings.WebGL.Small@2x", "BuildSettings.WebGL@2x", "BuildSettings.WP8", "BuildSettings.WP8.Small",
            "BuildSettings.Xbox360", "BuildSettings.Xbox360.Small", "BuildSettings.XboxOne On",
            "BuildSettings.XboxOne On@2x", "BuildSettings.XboxOne", "BuildSettings.XboxOne.Small",
            "BuildSettings.XboxOne.Small@2x", "BuildSettings.XboxOne@2x", "BuoyancyEffector2D Icon", "Button Icon",
            "CacheServerConnected", "CacheServerConnected@2x", "CacheServerDisabled", "CacheServerDisabled@2x",
            "CacheServerDisconnected", "CacheServerDisconnected@2x", "Camera Gizmo", "Camera Icon", "Canvas Icon",
            "CanvasGroup Icon", "CanvasRenderer Icon", "CanvasScaler Icon", "CapsuleCollider Icon",
            "CapsuleCollider2D Icon", "CGProgram Icon", "CharacterController Icon", "CharacterJoint Icon",
            "CheckerFloor", "ChorusFilter Icon", "CircleCollider2D Icon", "Clipboard", "Cloth Icon",
            "ClothInspector.PaintTool", "ClothInspector.PaintValue", "ClothInspector.SelectTool",
            "ClothInspector.SettingsTool", "ClothInspector.ViewValue", "CloudConnect", "CloudConnect@2x",
            "Collab.Build", "Collab.BuildFailed", "Collab.BuildSucceeded", "Collab.FileAdded", "Collab.FileConflict",
            "Collab.FileDeleted", "Collab.FileIgnored", "Collab.FileMoved", "Collab.FileUpdated", "Collab.FolderAdded",
            "Collab.FolderConflict", "Collab.FolderDeleted", "Collab.FolderIgnored", "Collab.FolderMoved",
            "Collab.FolderUpdated", "Collab.NoInternet", "Collab", "Collab.Warning", "Collab@2x", "CollabChanges Icon",
            "CollabChangesConflict Icon", "CollabChangesDeleted Icon", "CollabConflict Icon", "CollabConflict",
            "CollabCreate Icon", "CollabDeleted Icon", "CollabEdit Icon", "CollabError", "CollabExclude Icon",
            "CollabMoved Icon", "CollabNew", "CollabOffline", "CollabProgress", "CollabPull", "CollabPush",
            "ColorPicker.ColorCycle", "ColorPicker.CycleColor", "ColorPicker.CycleSlider", "ColorPicker.SliderCycle",
            "CompositeCollider2D Icon", "ComputeShader Icon", "ConfigurableJoint Icon", "conflict-icon",
            "conflict-icon@2x", "console.erroricon.inactive.sml", "console.erroricon.inactive.sml@2x",
            "console.erroricon", "console.erroricon.sml", "console.erroricon.sml@2x", "console.erroricon@2x",
            "console.infoicon.inactive.sml", "console.infoicon.inactive.sml@2x", "console.infoicon",
            "console.infoicon.sml", "console.infoicon.sml@2x", "console.infoicon@2x", "console.warnicon.inactive.sml",
            "console.warnicon.inactive.sml@2x", "console.warnicon", "console.warnicon.sml", "console.warnicon.sml@2x",
            "console.warnicon@2x", "ConstantForce Icon", "ConstantForce2D Icon", "ContentSizeFitter Icon",
            "CreateAddNew", "CreateAddNew@2x", "CrossIcon", "cs Script Icon", "Cubemap Icon", "curvekeyframe",
            "curvekeyframeselected", "curvekeyframeselectedoverlay", "curvekeyframesemiselectedoverlay",
            "curvekeyframeweighted", "CustomSorting", "CustomTool", "CustomTool@2x", "DebuggerAttached",
            "DebuggerAttached@2x", "DebuggerDisabled", "DebuggerDisabled@2x", "DebuggerEnabled", "DebuggerEnabled@2x",
            "DefaultAsset Icon", "DefaultSlate Icon", "DefaultSorting", "DefaultSorting@2x", "DirectionalLight Gizmo",
            "DirectionalLight Icon", "DiscLight Icon", "DistanceJoint2D Icon", "dll Script Icon", "DotFill", "DotFrame",
            "DotFrameDotted", "DotSelection", "Download-Available", "Download-Available@2x", "Dropdown Icon",
            "d_aboutwindow.mainheader", "d_ageialogo", "d_AimConstraint Icon", "d_align_horizontally",
            "d_align_horizontally_center", "d_align_horizontally_center_active", "d_align_horizontally_left",
            "d_align_horizontally_left_active", "d_align_horizontally_right", "d_align_horizontally_right_active",
            "d_align_vertically", "d_align_vertically_bottom", "d_align_vertically_bottom_active",
            "d_align_vertically_center", "d_align_vertically_center_active", "d_align_vertically_top",
            "d_align_vertically_top_active", "d_AlphabeticalSorting", "d_AlphabeticalSorting@2x",
            "d_AnalyticsTracker Icon", "d_Animation Icon", "d_Animation.AddEvent", "d_Animation.AddKeyframe",
            "d_Animation.EventMarker", "d_Animation.FilterBySelection", "d_Animation.FirstKey", "d_Animation.LastKey",
            "d_Animation.NextKey", "d_Animation.Play", "d_Animation.PrevKey", "d_Animation.Record",
            "d_Animation.Record@2x", "d_Animation.SequencerLink", "d_animationanimated", "d_AnimationClip Icon",
            "d_AnimationClip On Icon", "d_animationkeyframe", "d_animationnocurve", "d_animationvisibilitytoggleoff",
            "d_animationvisibilitytoggleoff@2x", "d_animationvisibilitytoggleon", "d_animationvisibilitytoggleon@2x",
            "d_AnimationWrapModeMenu", "d_Animator Icon", "d_AnimatorController Icon", "d_AnimatorController On Icon",
            "d_AnimatorOverrideController Icon", "d_AnimatorOverrideController On Icon", "d_AnimatorState Icon",
            "d_AnimatorStateMachine Icon", "d_AnimatorStateTransition Icon", "d_AnyStateNode Icon",
            "d_AreaEffector2D Icon", "d_AreaLight Icon", "d_AS Badge Delete", "d_AS Badge New",
            "d_AspectRatioFitter Icon", "d_Assembly Icon", "d_AssemblyDefinitionAsset Icon",
            "d_AssemblyDefinitionReferenceAsset Icon", "d_AssemblyLock", "d_Asset Store", "d_Asset Store@2x",
            "d_AssetStore Icon", "d_Audio Mixer", "d_Audio Mixer@2x", "d_AudioChorusFilter Icon", "d_AudioClip Icon",
            "d_AudioClip On Icon", "d_AudioDistortionFilter Icon", "d_AudioEchoFilter Icon",
            "d_AudioHighPassFilter Icon", "d_AudioImporter Icon", "d_AudioListener Icon", "d_AudioLowPassFilter Icon",
            "d_AudioMixerController Icon", "d_AudioMixerController On Icon", "d_AudioMixerGroup Icon",
            "d_AudioMixerSnapshot Icon", "d_AudioMixerView Icon", "d_AudioReverbFilter Icon", "d_AudioReverbZone Icon",
            "d_AudioSource Icon", "d_AudioSpatializerMicrosoft Icon", "d_AutoLightbakingOff", "d_AutoLightbakingOff@2x",
            "d_AutoLightbakingOn", "d_AutoLightbakingOn@2x", "d_Avatar Icon", "d_AvatarBlendBackground",
            "d_AvatarBlendLeft", "d_AvatarBlendLeftA", "d_AvatarBlendRight", "d_AvatarBlendRightA", "d_AvatarCompass",
            "d_AvatarMask Icon", "d_AvatarMask On Icon", "d_AvatarPivot", "d_AvatarPivot@2x", "d_AvatarSelector",
            "d_AvatarSelector@2x", "d_back", "d_back@2x", "d_beginButton-On", "d_beginButton", "d_BillboardAsset Icon",
            "d_BillboardRenderer Icon", "d_BlendTree Icon", "d_blueGroove", "d_boo Script Icon", "d_BoxCollider Icon",
            "d_BoxCollider2D Icon", "d_BuildSettings.Android", "d_BuildSettings.Android.Small",
            "d_BuildSettings.Android.Small@2x", "d_BuildSettings.Android@2x", "d_BuildSettings.Broadcom",
            "d_BuildSettings.Facebook", "d_BuildSettings.Facebook.Small", "d_BuildSettings.Facebook.Small@2x",
            "d_BuildSettings.Facebook@2x", "d_BuildSettings.FlashPlayer", "d_BuildSettings.FlashPlayer.Small",
            "d_BuildSettings.iPhone", "d_BuildSettings.iPhone.Small", "d_BuildSettings.iPhone.Small@2x",
            "d_BuildSettings.iPhone@2x", "d_BuildSettings.Lumin", "d_BuildSettings.Lumin.small",
            "d_BuildSettings.Lumin.small@2x", "d_BuildSettings.Lumin@2x", "d_BuildSettings.Metro",
            "d_BuildSettings.Metro.Small", "d_BuildSettings.Metro.Small@2x", "d_BuildSettings.Metro@2x",
            "d_BuildSettings.N3DS", "d_BuildSettings.N3DS.Small", "d_BuildSettings.N3DS.Small@2x",
            "d_BuildSettings.N3DS@2x", "d_BuildSettings.PS4", "d_BuildSettings.PS4.Small",
            "d_BuildSettings.PS4.Small@2x", "d_BuildSettings.PS4@2x", "d_BuildSettings.PSP2",
            "d_BuildSettings.PSP2.Small", "d_BuildSettings.SelectedIcon", "d_BuildSettings.Stadia",
            "d_BuildSettings.Stadia.Small", "d_BuildSettings.Stadia.Small@2x", "d_BuildSettings.Stadia@2x",
            "d_BuildSettings.Standalone", "d_BuildSettings.Standalone.Small", "d_BuildSettings.Standalone.Small@2x",
            "d_BuildSettings.Standalone@2x", "d_BuildSettings.Switch", "d_BuildSettings.Switch.Small",
            "d_BuildSettings.Switch.Small@2x", "d_BuildSettings.Switch@2x", "d_BuildSettings.tvOS",
            "d_BuildSettings.tvOS.Small", "d_BuildSettings.tvOS.Small@2x", "d_BuildSettings.tvOS@2x",
            "d_BuildSettings.Web", "d_BuildSettings.Web.Small", "d_BuildSettings.WebGL", "d_BuildSettings.WebGL.Small",
            "d_BuildSettings.WebGL.Small@2x", "d_BuildSettings.WebGL@2x", "d_BuildSettings.Xbox360",
            "d_BuildSettings.Xbox360.Small", "d_BuildSettings.XboxOne", "d_BuildSettings.XboxOne.Small",
            "d_BuildSettings.XboxOne.Small@2x", "d_BuildSettings.XboxOne@2x", "d_BuildSettings.Xiaomi",
            "d_BuildSettings.Xiaomi.Small", "d_BuildSettings.Xiaomi.Small@2x", "d_BuildSettings.Xiaomi@2x",
            "d_BuoyancyEffector2D Icon", "d_Button Icon", "d_CacheServerConnected", "d_CacheServerConnected@2x",
            "d_CacheServerDisabled", "d_CacheServerDisabled@2x", "d_CacheServerDisconnected",
            "d_CacheServerDisconnected@2x", "d_Camera Icon", "d_Canvas Icon", "d_CanvasGroup Icon",
            "d_CanvasRenderer Icon", "d_CanvasScaler Icon", "d_CapsuleCollider Icon", "d_CapsuleCollider2D Icon",
            "d_CGProgram Icon", "d_CharacterController Icon", "d_CharacterJoint Icon", "d_CheckerFloor",
            "d_CircleCollider2D Icon", "d_Cloth Icon", "d_CloudConnect", "d_CloudConnect@2x", "d_Collab.FileAdded",
            "d_Collab.FileConflict", "d_Collab.FileDeleted", "d_Collab.FileIgnored", "d_Collab.FileMoved",
            "d_Collab.FileUpdated", "d_Collab.FolderAdded", "d_Collab.FolderConflict", "d_Collab.FolderDeleted",
            "d_Collab.FolderIgnored", "d_Collab.FolderMoved", "d_Collab.FolderUpdated", "d_Collab", "d_Collab@2x",
            "d_CollabChanges Icon", "d_CollabChangesConflict Icon", "d_CollabChangesDeleted Icon",
            "d_CollabConflict Icon", "d_CollabCreate Icon", "d_CollabDeleted Icon", "d_CollabEdit Icon",
            "d_CollabExclude Icon", "d_CollabMoved Icon", "d_ColorPicker.CycleColor", "d_ColorPicker.CycleSlider",
            "d_CompositeCollider2D Icon", "d_ComputeShader Icon", "d_ConfigurableJoint Icon",
            "d_console.erroricon.inactive.sml", "d_console.erroricon.inactive.sml@2x", "d_console.erroricon",
            "d_console.erroricon.sml", "d_console.erroricon.sml@2x", "d_console.erroricon@2x",
            "d_console.infoicon.inactive.sml", "d_console.infoicon.inactive.sml@2x", "d_console.infoicon",
            "d_console.infoicon.sml", "d_console.infoicon.sml@2x", "d_console.infoicon@2x",
            "d_console.warnicon.inactive.sml", "d_console.warnicon.inactive.sml@2x", "d_console.warnicon",
            "d_console.warnicon.sml", "d_console.warnicon.sml@2x", "d_console.warnicon@2x", "d_ConstantForce Icon",
            "d_ConstantForce2D Icon", "d_ContentSizeFitter Icon", "d_CreateAddNew", "d_CreateAddNew@2x",
            "d_cs Script Icon", "d_Cubemap Icon", "d_curvekeyframe", "d_curvekeyframeselected",
            "d_curvekeyframeselectedoverlay", "d_curvekeyframesemiselectedoverlay", "d_curvekeyframeweighted",
            "d_CustomSorting", "d_CustomTool", "d_CustomTool@2x", "d_DebuggerAttached", "d_DebuggerAttached@2x",
            "d_DebuggerDisabled", "d_DebuggerDisabled@2x", "d_DebuggerEnabled", "d_DebuggerEnabled@2x",
            "d_DefaultAsset Icon", "d_DefaultSorting", "d_DefaultSorting@2x", "d_DirectionalLight Icon",
            "d_DistanceJoint2D Icon", "d_Dropdown Icon", "d_EdgeCollider2D Icon", "d_EditCollider",
            "d_editcollision_16", "d_editcollision_16@2x", "d_editcollision_32", "d_editconstraints_16",
            "d_editconstraints_16@2x", "d_editconstraints_32", "d_editicon.sml", "d_endButton-On", "d_endButton",
            "d_EventSystem Icon", "d_EventTrigger Icon", "d_Exposure", "d_Exposure@2x", "d_eyeDropper.Large",
            "d_eyeDropper.Large@2x", "d_eyeDropper.sml", "d_Favorite Icon", "d_Favorite On Icon", "d_Favorite",
            "d_Favorite@2x", "d_FilterByLabel", "d_FilterByLabel@2x", "d_FilterByType", "d_FilterByType@2x",
            "d_FilterSelectedOnly", "d_FilterSelectedOnly@2x", "d_FixedJoint Icon", "d_Flare Icon", "d_Flare On Icon",
            "d_FlareLayer Icon", "d_Folder Icon", "d_FolderEmpty Icon", "d_FolderEmpty On Icon",
            "d_FolderFavorite Icon", "d_FolderFavorite On Icon", "d_FolderOpened Icon", "d_Font Icon", "d_forward",
            "d_forward@2x", "d_FrameCapture", "d_FrameCapture@2x", "d_FreeformLayoutGroup Icon",
            "d_FrictionJoint2D Icon", "d_GameObject Icon", "d_GEAR", "d_GraphicRaycaster Icon", "d_greenLight",
            "d_Grid Icon", "d_Grid.BoxTool", "d_Grid.BoxTool@2x", "d_Grid.Default", "d_Grid.Default@2x",
            "d_Grid.EraserTool", "d_Grid.EraserTool@2x", "d_Grid.FillTool", "d_Grid.FillTool@2x", "d_Grid.MoveTool",
            "d_Grid.MoveTool@2x", "d_Grid.PaintTool", "d_Grid.PaintTool@2x", "d_Grid.PickingTool",
            "d_Grid.PickingTool@2x", "d_GridAxisX", "d_GridAxisX@2x", "d_GridAxisY", "d_GridAxisY@2x", "d_GridAxisZ",
            "d_GridAxisZ@2x", "d_GridLayoutGroup Icon", "d_Groove", "d_GUISkin Icon", "d_GUISkin On Icon",
            "d_Halo Icon", "d_HingeJoint Icon", "d_HingeJoint2D Icon", "d_HoloLensInputModule Icon",
            "d_HorizontalLayoutGroup Icon", "d_HorizontalSplit", "d_icon dropdown", "d_icon dropdown@2x",
            "d_IHVImageFormatImporter Icon", "d_Image Icon", "d_Import", "d_Import@2x", "d_InputField Icon",
            "d_InspectorLock", "d_Invalid", "d_Invalid@2x", "d_JointAngularLimits", "d_Js Script Icon",
            "d_LayoutElement Icon", "d_leftBracket", "d_Light Icon", "d_Lighting", "d_Lighting@2x",
            "d_LightingDataAsset Icon", "d_LightingDataAssetParent Icon", "d_LightingSettings Icon",
            "d_LightmapEditor.WindowTitle", "d_LightmapEditor.WindowTitle@2x", "d_LightmapParameters Icon",
            "d_LightmapParameters On Icon", "d_lightOff", "d_LightProbeGroup Icon", "d_LightProbeProxyVolume Icon",
            "d_LightProbes Icon", "d_lightRim", "d_LineRenderer Icon", "d_Linked", "d_Linked@2x", "d_LODGroup Icon",
            "d_LookAtConstraint Icon", "d_MainStageView", "d_MainStageView@2x", "d_Mask Icon", "d_Material Icon",
            "d_Material On Icon", "d_Mesh Icon", "d_MeshCollider Icon", "d_MeshFilter Icon", "d_MeshRenderer Icon",
            "d_Microphone Icon", "d_Mirror", "d_model large", "d_ModelImporter Icon", "d_monologo", "d_MoreOptions",
            "d_MoreOptions@2x", "d_Motion Icon", "d_MoveTool on", "d_MoveTool On@2x", "d_MoveTool", "d_MoveTool@2x",
            "d_Navigation", "d_NavMeshAgent Icon", "d_NavMeshData Icon", "d_NavMeshObstacle Icon",
            "d_NetworkAnimator Icon", "d_NetworkDiscovery Icon", "d_NetworkIdentity Icon", "d_NetworkLobbyManager Icon",
            "d_NetworkLobbyPlayer Icon", "d_NetworkManager Icon", "d_NetworkManagerHUD Icon",
            "d_NetworkMigrationManager Icon", "d_NetworkProximityChecker Icon", "d_NetworkStartPosition Icon",
            "d_NetworkTransform Icon", "d_NetworkTransformChild Icon", "d_NetworkTransformVisualizer Icon",
            "d_Occlusion", "d_Occlusion@2x", "d_OcclusionArea Icon", "d_OcclusionPortal Icon", "d_OffMeshLink Icon",
            "d_orangeLight", "d_Outline Icon", "d_Package Manager", "d_Package Manager@2x", "d_ParentConstraint Icon",
            "d_Particle Effect", "d_ParticleShapeTool On", "d_ParticleShapeTool On@2x", "d_ParticleShapeTool On@3x",
            "d_ParticleShapeTool On@4x", "d_ParticleShapeTool", "d_ParticleShapeTool@2x", "d_ParticleShapeTool@3x",
            "d_ParticleShapeTool@4x", "d_ParticleSystem Icon", "d_ParticleSystemForceField Icon", "d_PauseButton On",
            "d_PauseButton On@2x", "d_PauseButton", "d_PauseButton@2x", "d_PhysicalResolution Icon",
            "d_PhysicMaterial Icon", "d_PhysicMaterial On Icon", "d_Physics2DRaycaster Icon",
            "d_PhysicsMaterial2D Icon", "d_PhysicsMaterial2D On Icon", "d_PhysicsRaycaster Icon",
            "d_PlatformEffector2D Icon", "d_PlayableDirector Icon", "d_PlayButton On", "d_PlayButton On@2x",
            "d_PlayButton", "d_PlayButton@2x", "d_PlayButtonProfile On", "d_PlayButtonProfile", "d_playLoopOff",
            "d_playLoopOn", "d_PointEffector2D Icon", "d_PolygonCollider2D Icon", "d_PositionAsUV1 Icon",
            "d_PositionConstraint Icon", "d_preAudioAutoPlayOff", "d_preAudioAutoPlayOff@2x", "d_preAudioAutoPlayOn",
            "d_preAudioLoopOff", "d_preAudioLoopOff@2x", "d_preAudioLoopOn", "d_preAudioPlayOff", "d_preAudioPlayOn",
            "d_Prefab Icon", "d_Prefab On Icon", "d_PrefabModel Icon", "d_PrefabModel On Icon", "d_PrefabVariant Icon",
            "d_PrefabVariant On Icon", "d_PreMatCube", "d_PreMatCube@2x", "d_PreMatCylinder", "d_PreMatCylinder@2x",
            "d_PreMatLight0", "d_PreMatLight0@2x", "d_PreMatLight1", "d_PreMatLight1@2x", "d_PreMatQuad",
            "d_PreMatQuad@2x", "d_PreMatSphere", "d_PreMatSphere@2x", "d_PreMatTorus", "d_PreMatTorus@2x",
            "d_Preset.Context", "d_Preset.Context@2x", "d_PreTexA", "d_PreTexA@2x", "d_PreTexB", "d_PreTexB@2x",
            "d_PreTexG", "d_PreTexG@2x", "d_PreTexR", "d_PreTexR@2x", "d_PreTexRGB", "d_PreTexRGB@2x",
            "d_PreTextureAlpha", "d_PreTextureMipMapHigh", "d_PreTextureMipMapLow", "d_PreTextureRGB",
            "d_ProceduralMaterial Icon", "d_Profiler.Audio", "d_Profiler.Audio@2x", "d_Profiler.CPU",
            "d_Profiler.CPU@2x", "d_Profiler.FirstFrame", "d_Profiler.GlobalIllumination",
            "d_Profiler.GlobalIllumination@2x", "d_Profiler.GPU", "d_Profiler.GPU@2x", "d_Profiler.LastFrame",
            "d_Profiler.Memory", "d_Profiler.Memory@2x", "d_Profiler.Network", "d_Profiler.NetworkMessages",
            "d_Profiler.NetworkMessages@2x", "d_Profiler.NetworkOperations", "d_Profiler.NetworkOperations@2x",
            "d_Profiler.NextFrame", "d_Profiler.Physics", "d_Profiler.Physics2D", "d_Profiler.Physics2D@2x",
            "d_Profiler.Physics@2x", "d_Profiler.PrevFrame", "d_Profiler.Record", "d_Profiler.Rendering",
            "d_Profiler.Rendering@2x", "d_Profiler.UI", "d_Profiler.UI@2x", "d_Profiler.UIDetails",
            "d_Profiler.UIDetails@2x", "d_Profiler.Video", "d_Profiler.Video@2x", "d_ProfilerColumn.WarningCount",
            "d_Progress", "d_Progress@2x", "d_Project", "d_Project@2x", "d_Projector Icon", "d_RawImage Icon",
            "d_RaycastCollider Icon", "d_RayTracingShader Icon", "d_Record Off", "d_Record Off@2x", "d_Record On",
            "d_Record On@2x", "d_RectMask2D Icon", "d_RectTool On", "d_RectTool On@2x", "d_RectTool", "d_RectTool@2x",
            "d_RectTransform Icon", "d_RectTransformBlueprint", "d_RectTransformRaw", "d_redGroove", "d_redLight",
            "d_ReflectionProbe Icon", "d_ReflectionProbeSelector", "d_ReflectionProbeSelector@2x", "d_Refresh",
            "d_Refresh@2x", "d_RelativeJoint2D Icon", "d_RenderTexture Icon", "d_RenderTexture On Icon",
            "d_rightBracket", "d_Rigidbody Icon", "d_Rigidbody2D Icon", "d_RotateTool On", "d_RotateTool On@2x",
            "d_RotateTool", "d_RotateTool@2x", "d_RotationConstraint Icon", "d_SaveAs", "d_SaveAs@2x",
            "d_ScaleConstraint Icon", "d_ScaleTool On", "d_ScaleTool On@2x", "d_ScaleTool", "d_ScaleTool@2x",
            "d_SceneAsset Icon", "d_scenepicking_notpickable-mixed", "d_scenepicking_notpickable-mixed@2x",
            "d_scenepicking_notpickable-mixed_hover", "d_scenepicking_notpickable-mixed_hover@2x",
            "d_scenepicking_notpickable", "d_scenepicking_notpickable@2x", "d_scenepicking_notpickable_hover",
            "d_scenepicking_notpickable_hover@2x", "d_scenepicking_pickable-mixed", "d_scenepicking_pickable-mixed@2x",
            "d_scenepicking_pickable-mixed_hover", "d_scenepicking_pickable-mixed_hover@2x", "d_scenepicking_pickable",
            "d_scenepicking_pickable@2x", "d_scenepicking_pickable_hover", "d_scenepicking_pickable_hover@2x",
            "d_SceneView2D", "d_SceneView2D@2x", "d_SceneViewAlpha", "d_SceneViewAudio Off", "d_SceneViewAudio Off@2x",
            "d_SceneViewAudio", "d_SceneViewAudio@2x", "d_SceneViewCamera", "d_SceneViewCamera@2x", "d_SceneViewFx",
            "d_SceneViewFX@2x", "d_SceneViewLighting Off", "d_SceneViewLighting Off@2x", "d_SceneViewLighting",
            "d_SceneViewLighting@2x", "d_SceneViewOrtho", "d_SceneViewRGB", "d_SceneViewSnap-Off",
            "d_SceneViewSnap-Off@2x", "d_SceneViewSnap-On", "d_SceneViewSnap-On@2x", "d_SceneViewTools",
            "d_SceneViewTools@2x", "d_SceneViewVisibility", "d_SceneViewVisibility@2x", "d_scenevis_hidden-mixed",
            "d_scenevis_hidden-mixed@2x", "d_scenevis_hidden-mixed_hover", "d_scenevis_hidden-mixed_hover@2x",
            "d_scenevis_hidden", "d_scenevis_hidden@2x", "d_scenevis_hidden_hover", "d_scenevis_hidden_hover@2x",
            "d_scenevis_scene_hover", "d_scenevis_scene_hover@2x", "d_scenevis_visible-mixed",
            "d_scenevis_visible-mixed@2x", "d_scenevis_visible-mixed_hover", "d_scenevis_visible-mixed_hover@2x",
            "d_scenevis_visible", "d_scenevis_visible@2x", "d_scenevis_visible_hover", "d_scenevis_visible_hover@2x",
            "d_ScriptableObject Icon", "d_ScriptableObject On Icon", "d_Scrollbar Icon", "d_ScrollRect Icon",
            "d_ScrollShadow", "d_ScrollViewArea Icon", "d_Search Icon", "d_Selectable Icon", "d_SelectionList Icon",
            "d_SelectionListItem Icon", "d_SelectionListTemplate Icon", "d_Settings", "d_Settings@2x", "d_SettingsIcon",
            "d_SettingsIcon@2x", "d_Shader Icon", "d_ShaderImporter Icon", "d_ShaderVariantCollection Icon",
            "d_Shadow Icon", "d_SignalAsset Icon", "d_SignalEmitter Icon", "d_SignalReceiver Icon",
            "d_SkinnedMeshRenderer Icon", "d_Skybox Icon", "d_Slider Icon", "d_SliderJoint2D Icon",
            "d_SocialNetworks.FacebookShare", "d_SocialNetworks.LinkedInShare", "d_SocialNetworks.Tweet",
            "d_SocialNetworks.UDNOpen", "d_SortingGroup Icon", "d_SpatialMappingCollider Icon", "d_SpeedScale",
            "d_SphereCollider Icon", "d_Spotlight Icon", "d_SpringJoint Icon", "d_SpringJoint2D Icon", "d_Sprite Icon",
            "d_SpriteAtlas Icon", "d_SpriteAtlas On Icon", "d_SpriteAtlasAsset Icon", "d_SpriteAtlasImporter Icon",
            "d_SpriteMask Icon", "d_SpriteRenderer Icon", "d_SpriteShapeRenderer Icon", "d_StandaloneInputModule Icon",
            "d_StepButton On", "d_StepButton On@2x", "d_StepButton", "d_StepButton@2x", "d_StepLeftButton-On",
            "d_StepLeftButton", "d_StreamingController Icon", "d_StyleSheet Icon", "d_SurfaceEffector2D Icon",
            "d_tab_next", "d_tab_next@2x", "d_tab_prev", "d_tab_prev@2x", "d_TargetJoint2D Icon", "d_Terrain Icon",
            "d_TerrainCollider Icon", "d_TerrainData Icon", "d_TerrainInspector.TerrainToolLower On",
            "d_TerrainInspector.TerrainToolLowerAlt", "d_TerrainInspector.TerrainToolPlants On",
            "d_TerrainInspector.TerrainToolPlants", "d_TerrainInspector.TerrainToolPlantsAlt On",
            "d_TerrainInspector.TerrainToolPlantsAlt", "d_TerrainInspector.TerrainToolRaise On",
            "d_TerrainInspector.TerrainToolRaise", "d_TerrainInspector.TerrainToolSetheight On",
            "d_TerrainInspector.TerrainToolSetheight", "d_TerrainInspector.TerrainToolSetheightAlt On",
            "d_TerrainInspector.TerrainToolSetheightAlt", "d_TerrainInspector.TerrainToolSettings On",
            "d_TerrainInspector.TerrainToolSettings", "d_TerrainInspector.TerrainToolSmoothHeight On",
            "d_TerrainInspector.TerrainToolSmoothHeight", "d_TerrainInspector.TerrainToolSplat On",
            "d_TerrainInspector.TerrainToolSplat", "d_TerrainInspector.TerrainToolSplatAlt On",
            "d_TerrainInspector.TerrainToolSplatAlt", "d_TerrainInspector.TerrainToolTrees On",
            "d_TerrainInspector.TerrainToolTrees", "d_TerrainInspector.TerrainToolTreesAlt On",
            "d_TerrainInspector.TerrainToolTreesAlt", "d_Text Icon", "d_TextAsset Icon", "d_TextScriptImporter Icon",
            "d_Texture Icon", "d_Texture2D Icon", "d_TextureImporter Icon", "d_Tile Icon", "d_Tilemap Icon",
            "d_TilemapCollider2D Icon", "d_TilemapRenderer Icon", "d_TimelineAsset Icon", "d_TimelineAsset On Icon",
            "d_Toggle Icon", "d_ToggleGroup Icon", "d_ToggleUVOverlay", "d_ToggleUVOverlay@2x", "d_Toolbar Minus",
            "d_Toolbar Minus@2x", "d_Toolbar Plus More", "d_Toolbar Plus More@2x", "d_Toolbar Plus",
            "d_Toolbar Plus@2x", "d_ToolHandleCenter", "d_ToolHandleCenter@2x", "d_ToolHandleGlobal",
            "d_ToolHandleGlobal@2x", "d_ToolHandleLocal", "d_ToolHandleLocal@2x", "d_ToolHandlePivot",
            "d_ToolHandlePivot@2x", "d_ToolsIcon", "d_TouchInputModule Icon", "d_TrailRenderer Icon", "d_tranp",
            "d_Transform Icon", "d_TransformTool On", "d_TransformTool On@2x", "d_TransformTool", "d_TransformTool@2x",
            "d_TreeEditor.AddBranches", "d_TreeEditor.AddLeaves", "d_TreeEditor.Branch On", "d_TreeEditor.Branch",
            "d_TreeEditor.BranchFreeHand On", "d_TreeEditor.BranchFreeHand", "d_TreeEditor.BranchRotate On",
            "d_TreeEditor.BranchRotate", "d_TreeEditor.BranchScale On", "d_TreeEditor.BranchScale",
            "d_TreeEditor.BranchTranslate On", "d_TreeEditor.BranchTranslate", "d_TreeEditor.Distribution On",
            "d_TreeEditor.Distribution", "d_TreeEditor.Duplicate", "d_TreeEditor.Geometry On", "d_TreeEditor.Geometry",
            "d_TreeEditor.Leaf On", "d_TreeEditor.Leaf", "d_TreeEditor.LeafFreeHand On", "d_TreeEditor.LeafFreeHand",
            "d_TreeEditor.LeafRotate On", "d_TreeEditor.LeafRotate", "d_TreeEditor.LeafScale On",
            "d_TreeEditor.LeafScale", "d_TreeEditor.LeafTranslate On", "d_TreeEditor.LeafTranslate",
            "d_TreeEditor.Material On", "d_TreeEditor.Material", "d_TreeEditor.Refresh", "d_TreeEditor.Trash",
            "d_TreeEditor.Wind On", "d_TreeEditor.Wind", "d_tree_icon", "d_tree_icon_branch",
            "d_tree_icon_branch_frond", "d_tree_icon_frond", "d_tree_icon_leaf", "d_TrueTypeFontImporter Icon",
            "d_UnityEditor.AnimationWindow", "d_UnityEditor.AnimationWindow@2x", "d_UnityEditor.ConsoleWindow",
            "d_UnityEditor.ConsoleWindow@2x", "d_UnityEditor.DebugInspectorWindow", "d_UnityEditor.FindDependencies",
            "d_UnityEditor.GameView", "d_UnityEditor.GameView@2x", "d_UnityEditor.Graphs.AnimatorControllerTool",
            "d_UnityEditor.Graphs.AnimatorControllerTool@2x", "d_UnityEditor.HierarchyWindow",
            "d_UnityEditor.InspectorWindow", "d_UnityEditor.InspectorWindow@2x", "d_UnityEditor.ProfilerWindow",
            "d_UnityEditor.ProfilerWindow@2x", "d_UnityEditor.SceneHierarchyWindow",
            "d_UnityEditor.SceneHierarchyWindow@2x", "d_UnityEditor.SceneView", "d_UnityEditor.SceneView@2x",
            "d_UnityEditor.Timeline.TimelineWindow", "d_UnityEditor.Timeline.TimelineWindow@2x",
            "d_UnityEditor.VersionControl", "d_UnityLogo", "d_Unlinked", "d_Unlinked@2x", "d_Valid", "d_Valid@2x",
            "d_VerticalLayoutGroup Icon", "d_VerticalSplit", "d_VideoPlayer Icon", "d_ViewToolMove On",
            "d_ViewToolMove On@2x", "d_ViewToolMove", "d_ViewToolMove@2x", "d_ViewToolOrbit On",
            "d_ViewToolOrbit On@2x", "d_ViewToolOrbit", "d_ViewToolOrbit@2x", "d_ViewToolZoom On",
            "d_ViewToolZoom On@2x", "d_ViewToolZoom", "d_ViewToolZoom@2x", "d_VisibilityOff", "d_VisibilityOn",
            "d_VisualEffect Icon", "d_VisualEffectAsset Icon", "d_VisualEffectSubgraphBlock Icon",
            "d_VisualEffectSubgraphOperator Icon", "d_VisualTreeAsset Icon", "d_VUMeterTextureHorizontal",
            "d_VUMeterTextureVertical", "d_WaitSpin00", "d_WaitSpin01", "d_WaitSpin02", "d_WaitSpin03", "d_WaitSpin04",
            "d_WaitSpin05", "d_WaitSpin06", "d_WaitSpin07", "d_WaitSpin08", "d_WaitSpin09", "d_WaitSpin10",
            "d_WaitSpin11", "d_WelcomeScreen.AssetStoreLogo", "d_WheelCollider Icon", "d_WheelJoint2D Icon",
            "d_winbtn_graph", "d_winbtn_graph_close_h", "d_winbtn_graph_max_h", "d_winbtn_graph_min_h",
            "d_winbtn_mac_close", "d_winbtn_mac_close@2x", "d_winbtn_mac_close_a", "d_winbtn_mac_close_a@2x",
            "d_winbtn_mac_close_h", "d_winbtn_mac_close_h@2x", "d_winbtn_mac_inact", "d_winbtn_mac_max",
            "d_winbtn_mac_max@2x", "d_winbtn_mac_max_a", "d_winbtn_mac_max_a@2x", "d_winbtn_mac_max_h",
            "d_winbtn_mac_max_h@2x", "d_winbtn_mac_min", "d_winbtn_mac_min@2x", "d_winbtn_mac_min_a",
            "d_winbtn_mac_min_a@2x", "d_winbtn_mac_min_h", "d_winbtn_mac_min_h@2x", "d_winbtn_win_close",
            "d_winbtn_win_close@2x", "d_winbtn_win_close_a", "d_winbtn_win_close_a@2x", "d_winbtn_win_close_h",
            "d_winbtn_win_close_h@2x", "d_winbtn_win_max", "d_winbtn_win_max@2x", "d_winbtn_win_max_a",
            "d_winbtn_win_max_a@2x", "d_winbtn_win_max_h", "d_winbtn_win_max_h@2x", "d_winbtn_win_min",
            "d_winbtn_win_min_a", "d_winbtn_win_min_h", "d_winbtn_win_rest", "d_winbtn_win_restore",
            "d_winbtn_win_restore@2x", "d_winbtn_win_restore_a", "d_winbtn_win_restore_a@2x", "d_winbtn_win_restore_h",
            "d_winbtn_win_restore_h@2x", "d_winbtn_win_rest_a", "d_winbtn_win_rest_h", "d_WindZone Icon", "d__Help",
            "d__Help@2x", "d__Menu", "d__Menu@2x", "d__Popup", "d__Popup@2x", "EchoFilter Icon", "EdgeCollider2D Icon",
            "EditCollider", "editcollision_16", "editcollision_16@2x", "editcollision_32", "editconstraints_16",
            "editconstraints_16@2x", "editconstraints_32", "editicon.sml", "EditorSettings Icon", "endButton-On",
            "endButton", "Error", "Error@2x", "EventSystem Icon", "EventTrigger Icon", "Exposure", "Exposure@2x",
            "eyeDropper.Large", "eyeDropper.Large@2x", "eyeDropper.sml", "Favorite Icon", "Favorite On Icon",
            "Favorite", "Favorite@2x", "FilterByLabel", "FilterByLabel@2x", "FilterByType", "FilterByType@2x",
            "FilterSelectedOnly", "FilterSelectedOnly@2x", "FixedJoint Icon", "FixedJoint2D Icon", "Flare Icon",
            "Flare On Icon", "FlareLayer Icon", "Folder Icon", "Folder On Icon", "FolderEmpty Icon",
            "FolderEmpty On Icon", "FolderFavorite Icon", "FolderFavorite On Icon", "FolderOpened Icon",
            "FolderOpened On Icon", "Font Icon", "Font On Icon", "forward", "forward@2x", "FrameCapture",
            "FrameCapture@2x", "FreeformLayoutGroup Icon", "FrictionJoint2D Icon", "GameManager Icon",
            "GameObject Icon", "GameObject On Icon", "GEAR", "GraphicRaycaster Icon", "greenLight", "Grid Icon",
            "Grid.BoxTool", "Grid.BoxTool@2x", "Grid.Default", "Grid.Default@2x", "Grid.EraserTool",
            "Grid.EraserTool@2x", "Grid.FillTool", "Grid.FillTool@2x", "Grid.MoveTool", "Grid.MoveTool@2x",
            "Grid.PaintTool", "Grid.PaintTool@2x", "Grid.PickingTool", "Grid.PickingTool@2x", "GridAxisX",
            "GridAxisX@2x", "GridAxisY", "GridAxisY@2x", "GridAxisZ", "GridAxisZ@2x", "GridBrush Icon",
            "GridLayoutGroup Icon", "Groove", "GUILayer Icon", "GUISkin Icon", "GUISkin On Icon", "GUIText Icon",
            "GUITexture Icon", "Halo Icon", "Head", "HeadIk", "HeadZoom", "HeadZoomSilhouette", "HighPassFilter Icon",
            "HingeJoint Icon", "HingeJoint2D Icon", "HoloLensInputModule Icon", "HorizontalLayoutGroup Icon",
            "HorizontalSplit", "HumanTemplate Icon", "icon dropdown", "icon dropdown@2x", "IHVImageFormatImporter Icon",
            "Image Icon", "Import-Available", "Import-Available@2x", "Import", "Import@2x",
            "In-Development", "In-Development@2x",
            "InputField Icon", "InspectorLock", "Installed", "Installed@2x", "Invalid", "Invalid@2x",
            "JointAngularLimits", "Js Script Icon", "KnobCShape", "KnobCShapeMini", "LayoutElement Icon", "LeftArm",
            "leftBracket", "LeftFeetIk", "LeftFingers", "LeftFingersIk", "LeftHandZoom", "LeftHandZoomSilhouette",
            "LeftLeg", "LensFlare Gizmo", "LensFlare Icon", "Light Icon", "Lighting", "Lighting@2x",
            "LightingDataAsset Icon", "LightingDataAssetParent Icon", "LightingSettings Icon",
            "LightmapEditor.WindowTitle", "LightmapEditor.WindowTitle@2x", "LightmapParameters Icon",
            "LightmapParameters On Icon", "Lightmapping", "lightOff", "LightProbeGroup Gizmo", "LightProbeGroup Icon",
            "LightProbeProxyVolume Gizmo", "LightProbeProxyVolume Icon", "LightProbes Icon", "lightRim",
            "LineRenderer Icon", "Linked", "Linked@2x", "Loading", "Loading@2x", "LockIcon-On", "LockIcon",
            "LODGroup Icon", "LookAtConstraint Icon", "loop", "LowPassFilter Icon", "Main Light Gizmo", "MainStageView",
            "MainStageView@2x", "Mask Icon", "MaskEditor_Root", "Material Icon", "Material On Icon", "Mesh Icon",
            "MeshCollider Icon", "MeshFilter Icon", "MeshRenderer Icon", "MetaFile Icon", "Microphone Icon", "Mirror",
            "ModelImporter Icon", "monologo", "MoreOptions", "MoreOptions@2x", "Motion Icon", "MoveTool on",
            "MoveTool On@2x", "MoveTool", "MoveTool@2x", "MovieTexture Icon", "MuscleClip Icon", "Navigation",
            "NavMeshAgent Icon", "NavMeshData Icon", "NavMeshObstacle Icon", "NetworkAnimator Icon",
            "NetworkDiscovery Icon", "NetworkIdentity Icon", "NetworkLobbyManager Icon", "NetworkLobbyPlayer Icon",
            "NetworkManager Icon", "NetworkManagerHUD Icon", "NetworkMigrationManager Icon",
            "NetworkProximityChecker Icon", "NetworkStartPosition Icon", "NetworkTransform Icon",
            "NetworkTransformChild Icon", "NetworkTransformVisualizer Icon", "NetworkView Icon", "Occlusion",
            "Occlusion@2x", "OcclusionArea Icon", "OcclusionPortal Icon", "OffMeshLink Icon", "orangeLight",
            "Outline Icon", "P4_AddedLocal", "P4_AddedLocal@2x", "P4_AddedRemote", "P4_AddedRemote@2x",
            "P4_BlueLeftParenthesis", "P4_BlueLeftParenthesis@2x", "P4_BlueRightParenthesis",
            "P4_BlueRightParenthesis@2x", "P4_CheckOutLocal", "P4_CheckOutLocal@2x", "P4_CheckOutRemote",
            "P4_CheckOutRemote@2x", "P4_Conflicted", "P4_Conflicted@2x", "P4_DeletedLocal", "P4_DeletedLocal@2x",
            "P4_DeletedRemote", "P4_DeletedRemote@2x", "P4_Local", "P4_Local@2x", "P4_LockedLocal", "P4_LockedLocal@2x",
            "P4_LockedRemote", "P4_LockedRemote@2x", "P4_OutOfSync", "P4_OutOfSync@2x", "P4_RedLeftParenthesis",
            "P4_RedLeftParenthesis@2x", "P4_RedRightParenthesis", "P4_RedRightParenthesis@2x", "P4_Updating",
            "P4_Updating@2x", "Package Manager", "Package Manager@2x", "PackageBadgeDelete", "PackageBadgeNew",
            "ParentConstraint Icon", "Particle Effect", "ParticleShapeTool On", "ParticleShapeTool On@2x",
            "ParticleShapeTool On@3x", "ParticleShapeTool On@4x", "ParticleShapeTool", "ParticleShapeTool@2x",
            "ParticleShapeTool@3x", "ParticleShapeTool@4x", "ParticleSystem Gizmo", "ParticleSystem Icon",
            "ParticleSystemForceField Gizmo", "ParticleSystemForceField Icon", "PauseButton On", "PauseButton On@2x",
            "PauseButton", "PauseButton@2x", "PhysicMaterial Icon", "PhysicMaterial On Icon", "Physics2DRaycaster Icon",
            "PhysicsMaterial2D Icon", "PhysicsMaterial2D On Icon", "PhysicsRaycaster Icon", "PlatformEffector2D Icon",
            "PlayableDirector Icon", "PlayButton On", "PlayButton On@2x", "PlayButton", "PlayButton@2x",
            "PlayButtonProfile On", "PlayButtonProfile", "playLoopOff", "playLoopOn", "playSpeed",
            "PointEffector2D Icon", "PointLight Gizmo", "PolygonCollider2D Icon", "PositionAsUV1 Icon",
            "PositionConstraint Icon", "preAudioAutoPlayOff", "preAudioAutoPlayOff@2x", "preAudioAutoPlayOn",
            "preAudioLoopOff", "preAudioLoopOff@2x", "preAudioLoopOn", "preAudioPlayOff", "preAudioPlayOn",
            "Prefab Icon", "Prefab On Icon", "PrefabModel Icon", "PrefabModel On Icon", "PrefabOverlayAdded Icon",
            "PrefabOverlayModified Icon", "PrefabOverlayRemoved Icon", "PrefabVariant Icon", "PrefabVariant On Icon",
            "PreMatCube", "PreMatCube@2x", "PreMatCylinder", "PreMatCylinder@2x", "PreMatLight0", "PreMatLight0@2x",
            "PreMatLight1", "PreMatLight1@2x", "PreMatQuad", "PreMatQuad@2x", "PreMatSphere", "PreMatSphere@2x",
            "PreMatTorus", "PreMatTorus@2x", "Preset Icon", "Preset.Context", "Preset.Context@2x", "PreTexA",
            "PreTexA@2x", "PreTexB", "PreTexB@2x", "PreTexG", "PreTexG@2x", "PreTexR", "PreTexR@2x", "PreTexRGB",
            "PreTexRGB@2x", "PreTextureAlpha", "PreTextureArrayFirstSlice", "PreTextureArrayLastSlice",
            "PreTextureMipMapHigh", "PreTextureMipMapLow", "PreTextureRGB", "PreviewPackageInUse",
            "PreviewPackageInUse@2x", "ProceduralMaterial Icon", "Profiler.Audio", "Profiler.Audio@2x", "Profiler.CPU",
            "Profiler.CPU@2x", "Profiler.FirstFrame", "Profiler.GlobalIllumination", "Profiler.GlobalIllumination@2x",
            "Profiler.GPU", "Profiler.GPU@2x", "Profiler.Instrumentation", "Profiler.LastFrame", "Profiler.Memory",
            "Profiler.Memory@2x", "Profiler.NetworkMessages", "Profiler.NetworkMessages@2x",
            "Profiler.NetworkOperations", "Profiler.NetworkOperations@2x", "Profiler.NextFrame", "Profiler.Physics",
            "Profiler.Physics2D", "Profiler.Physics2D@2x", "Profiler.Physics@2x", "Profiler.PrevFrame",
            "Profiler.Record", "Profiler.Rendering", "Profiler.Rendering@2x", "Profiler.UI", "Profiler.UI@2x",
            "Profiler.UIDetails", "Profiler.UIDetails@2x", "Profiler.Video", "Profiler.Video@2x",
            "ProfilerColumn.WarningCount", "Progress", "Progress@2x", "Project", "Project@2x", "Projector Gizmo",
            "Projector Icon", "RawImage Icon", "RaycastCollider Icon", "RayTracingShader Icon", "Record Off",
            "Record Off@2x", "Record On", "Record On@2x", "RectMask2D Icon", "RectTool On", "RectTool On@2x",
            "RectTool", "RectTool@2x", "RectTransform Icon", "RectTransformBlueprint", "RectTransformRaw", "redGroove",
            "redLight", "ReflectionProbe Gizmo", "ReflectionProbe Icon", "ReflectionProbeSelector",
            "ReflectionProbeSelector@2x", "Refresh", "Refresh@2x", "RelativeJoint2D Icon", "RenderTexture Icon",
            "RenderTexture On Icon", "ReverbFilter Icon", "RightArm", "rightBracket", "RightFeetIk", "RightFingers",
            "RightFingersIk", "RightHandZoom", "RightHandZoomSilhouette", "RightLeg", "Rigidbody Icon",
            "Rigidbody2D Icon", "RotateTool On", "RotateTool On@2x", "RotateTool", "RotateTool@2x", "RotateTool@4x",
            "RotationConstraint Icon", "SaveActive", "SaveAs", "SaveAs@2x", "SaveFromPlay", "SavePassive",
            "ScaleConstraint Icon", "ScaleTool On", "ScaleTool On@2x", "ScaleTool", "ScaleTool@2x", "SceneAsset Icon",
            "SceneAsset On Icon", "SceneLoadIn", "SceneLoadOut", "scenepicking_notpickable-mixed",
            "scenepicking_notpickable-mixed@2x", "scenepicking_notpickable-mixed_hover",
            "scenepicking_notpickable-mixed_hover@2x", "scenepicking_notpickable", "scenepicking_notpickable@2x",
            "scenepicking_notpickable_hover", "scenepicking_notpickable_hover@2x", "scenepicking_pickable-mixed",
            "scenepicking_pickable-mixed@2x", "scenepicking_pickable-mixed_hover",
            "scenepicking_pickable-mixed_hover@2x", "scenepicking_pickable", "scenepicking_pickable@2x",
            "scenepicking_pickable_hover", "scenepicking_pickable_hover@2x", "SceneSave", "SceneSaveGrey",
            "SceneSet Icon", "SceneView2D", "SceneView2D@2x", "SceneViewAlpha", "SceneViewAudio Off",
            "SceneViewAudio Off@2x", "SceneViewAudio", "SceneViewAudio@2x", "SceneViewCamera", "SceneViewCamera@2x",
            "SceneViewFx", "SceneViewFX@2x", "SceneViewLighting Off", "SceneViewLighting Off@2x", "SceneViewLighting",
            "SceneViewLighting@2x", "SceneViewOrtho", "SceneViewRGB", "SceneViewSnap-Off", "SceneViewSnap-Off@2x",
            "SceneViewSnap-On", "SceneViewSnap-On@2x", "SceneViewTools", "SceneViewTools@2x", "SceneViewVisibility",
            "SceneViewVisibility@2x", "scenevis_hidden-mixed", "scenevis_hidden-mixed@2x",
            "scenevis_hidden-mixed_hover", "scenevis_hidden-mixed_hover@2x", "scenevis_hidden", "scenevis_hidden@2x",
            "scenevis_hidden_hover", "scenevis_hidden_hover@2x", "scenevis_scene_hover", "scenevis_scene_hover@2x",
            "scenevis_visible-mixed", "scenevis_visible-mixed@2x", "scenevis_visible-mixed_hover",
            "scenevis_visible-mixed_hover@2x", "scenevis_visible", "scenevis_visible@2x", "scenevis_visible_hover",
            "scenevis_visible_hover@2x", "ScriptableObject Icon", "ScriptableObject On Icon", "Scrollbar Icon",
            "ScrollRect Icon", "ScrollShadow", "Search Icon", "Search On Icon", "Selectable Icon", "Settings",
            "Settings@2x", "SettingsIcon", "SettingsIcon@2x", "Shader Icon", "ShaderImporter Icon",
            "ShaderVariantCollection Icon", "Shadow Icon", "SignalAsset Icon", "SignalEmitter Icon",
            "SignalReceiver Icon", "SkinnedMeshRenderer Icon", "Skybox Icon", "Slider Icon", "SliderJoint2D Icon",
            "SocialNetworks.FacebookShare", "SocialNetworks.LinkedInShare", "SocialNetworks.Tweet",
            "SocialNetworks.UDNLogo", "SocialNetworks.UDNOpen", "SoftlockInline", "SoftlockProjectBrowser Icon",
            "SortingGroup Icon", "SpatialMappingCollider Icon", "SpatialMappingRenderer Icon", "SpeedScale",
            "SpeedTreeImporter Icon", "SpeedTreeModel Icon", "SphereCollider Icon", "SpotLight Gizmo", "Spotlight Icon",
            "SpringJoint Icon", "SpringJoint2D Icon", "Sprite Icon", "SpriteAtlas Icon", "SpriteAtlas On Icon",
            "SpriteAtlasAsset Icon", "SpriteAtlasImporter Icon", "SpriteCollider Icon", "SpriteMask Icon",
            "SpriteRenderer Icon", "SpriteShapeRenderer Icon", "StandaloneInputModule Icon",
            "StateMachineEditor.ArrowTip", "StateMachineEditor.ArrowTipSelected", "StateMachineEditor.Background",
            "StateMachineEditor.State", "StateMachineEditor.StateHover", "StateMachineEditor.StateSelected",
            "StateMachineEditor.StateSub", "StateMachineEditor.StateSubHover", "StateMachineEditor.StateSubSelected",
            "StateMachineEditor.UpButton", "StateMachineEditor.UpButtonHover", "StepButton On", "StepButton On@2x",
            "StepButton", "StepButton@2x", "StepLeftButton-On", "StepLeftButton", "StreamingController Icon",
            "StyleSheet Icon", "SubstanceArchive Icon", "SurfaceEffector2D Icon", "sv_icon_dot0_pix16_gizmo",
            "sv_icon_dot0_sml", "sv_icon_dot10_pix16_gizmo", "sv_icon_dot10_sml", "sv_icon_dot11_pix16_gizmo",
            "sv_icon_dot11_sml", "sv_icon_dot12_pix16_gizmo", "sv_icon_dot12_sml", "sv_icon_dot13_pix16_gizmo",
            "sv_icon_dot13_sml", "sv_icon_dot14_pix16_gizmo", "sv_icon_dot14_sml", "sv_icon_dot15_pix16_gizmo",
            "sv_icon_dot15_sml", "sv_icon_dot1_pix16_gizmo", "sv_icon_dot1_sml", "sv_icon_dot2_pix16_gizmo",
            "sv_icon_dot2_sml", "sv_icon_dot3_pix16_gizmo", "sv_icon_dot3_sml", "sv_icon_dot4_pix16_gizmo",
            "sv_icon_dot4_sml", "sv_icon_dot5_pix16_gizmo", "sv_icon_dot5_sml", "sv_icon_dot6_pix16_gizmo",
            "sv_icon_dot6_sml", "sv_icon_dot7_pix16_gizmo", "sv_icon_dot7_sml", "sv_icon_dot8_pix16_gizmo",
            "sv_icon_dot8_sml", "sv_icon_dot9_pix16_gizmo", "sv_icon_dot9_sml", "sv_icon_name0", "sv_icon_name1",
            "sv_icon_name2", "sv_icon_name3", "sv_icon_name4", "sv_icon_name5", "sv_icon_name6", "sv_icon_name7",
            "sv_icon_none", "sv_label_0", "sv_label_1", "sv_label_2", "sv_label_3", "sv_label_4", "sv_label_5",
            "sv_label_6", "sv_label_7", "tab_next", "tab_next@2x", "tab_prev", "tab_prev@2x", "TargetJoint2D Icon",
            "Terrain Icon", "TerrainCollider Icon", "TerrainData Icon", "TerrainInspector.TerrainToolAdd",
            "TerrainInspector.TerrainToolLower On", "TerrainInspector.TerrainToolLower",
            "TerrainInspector.TerrainToolLowerAlt", "TerrainInspector.TerrainToolPlants On",
            "TerrainInspector.TerrainToolPlants", "TerrainInspector.TerrainToolPlantsAlt On",
            "TerrainInspector.TerrainToolPlantsAlt", "TerrainInspector.TerrainToolRaise On",
            "TerrainInspector.TerrainToolRaise", "TerrainInspector.TerrainToolSculpt On",
            "TerrainInspector.TerrainToolSculpt", "TerrainInspector.TerrainToolSetheight On",
            "TerrainInspector.TerrainToolSetheight", "TerrainInspector.TerrainToolSetheightAlt On",
            "TerrainInspector.TerrainToolSetheightAlt", "TerrainInspector.TerrainToolSettings On",
            "TerrainInspector.TerrainToolSettings", "TerrainInspector.TerrainToolSmoothHeight On",
            "TerrainInspector.TerrainToolSmoothHeight", "TerrainInspector.TerrainToolSplat On",
            "TerrainInspector.TerrainToolSplat", "TerrainInspector.TerrainToolSplatAlt On",
            "TerrainInspector.TerrainToolSplatAlt", "TerrainInspector.TerrainToolTrees On",
            "TerrainInspector.TerrainToolTrees", "TerrainInspector.TerrainToolTreesAlt On",
            "TerrainInspector.TerrainToolTreesAlt", "TestFailed", "TestIgnored", "TestInconclusive", "TestNormal",
            "TestPassed", "TestStopwatch", "Text Icon", "TextAsset Icon", "TextMesh Icon", "TextScriptImporter Icon",
            "Texture Icon", "Texture2D Icon", "TextureImporter Icon", "Tile Icon", "Tilemap Icon",
            "TilemapCollider2D Icon", "TilemapRenderer Icon", "TimelineAsset Icon", "TimelineAsset On Icon",
            "Toggle Icon", "ToggleGroup Icon", "ToggleUVOverlay", "ToggleUVOverlay@2x", "Toolbar Minus",
            "Toolbar Minus@2x", "Toolbar Plus More", "Toolbar Plus More@2x", "Toolbar Plus", "Toolbar Plus@2x",
            "ToolHandleCenter", "ToolHandleCenter@2x", "ToolHandleGlobal", "ToolHandleGlobal@2x", "ToolHandleLocal",
            "ToolHandleLocal@2x", "ToolHandlePivot", "ToolHandlePivot@2x", "ToolsIcon", "Torso",
            "TouchInputModule Icon", "TrackedPoseDriver Icon", "TrailRenderer Icon", "tranp", "Transform Icon",
            "TransformTool On", "TransformTool On@2x", "TransformTool", "TransformTool@2x", "TreeEditor.AddBranches",
            "TreeEditor.AddLeaves", "TreeEditor.Branch On", "TreeEditor.Branch", "TreeEditor.BranchFreeHand On",
            "TreeEditor.BranchFreeHand", "TreeEditor.BranchRotate On", "TreeEditor.BranchRotate",
            "TreeEditor.BranchScale On", "TreeEditor.BranchScale", "TreeEditor.BranchTranslate On",
            "TreeEditor.BranchTranslate", "TreeEditor.Distribution On", "TreeEditor.Distribution",
            "TreeEditor.Duplicate", "TreeEditor.Geometry On", "TreeEditor.Geometry", "TreeEditor.Leaf On",
            "TreeEditor.Leaf", "TreeEditor.LeafFreeHand On", "TreeEditor.LeafFreeHand", "TreeEditor.LeafRotate On",
            "TreeEditor.LeafRotate", "TreeEditor.LeafScale On", "TreeEditor.LeafScale", "TreeEditor.LeafTranslate On",
            "TreeEditor.LeafTranslate", "TreeEditor.Material On", "TreeEditor.Material", "TreeEditor.Refresh",
            "TreeEditor.Trash", "TreeEditor.Wind On", "TreeEditor.Wind", "tree_icon", "tree_icon_branch",
            "tree_icon_branch_frond", "tree_icon_frond", "tree_icon_leaf", "TrueTypeFontImporter Icon",
            "Unity-AssetStore-Originals-Logo-White", "Unity-AssetStore-Originals-Logo-White@2x",
            "UnityEditor.AnimationWindow", "UnityEditor.AnimationWindow@2x", "UnityEditor.ConsoleWindow",
            "UnityEditor.ConsoleWindow@2x", "UnityEditor.DebugInspectorWindow", "UnityEditor.FindDependencies",
            "UnityEditor.GameView", "UnityEditor.GameView@2x", "UnityEditor.Graphs.AnimatorControllerTool",
            "UnityEditor.Graphs.AnimatorControllerTool@2x", "UnityEditor.HierarchyWindow",
            "UnityEditor.HierarchyWindow@2x", "UnityEditor.InspectorWindow", "UnityEditor.InspectorWindow@2x",
            "UnityEditor.ProfilerWindow", "UnityEditor.ProfilerWindow@2x", "UnityEditor.SceneHierarchyWindow",
            "UnityEditor.SceneHierarchyWindow@2x", "UnityEditor.SceneView", "UnityEditor.SceneView@2x",
            "UnityEditor.Timeline.TimelineWindow", "UnityEditor.Timeline.TimelineWindow@2x",
            "UnityEditor.VersionControl", "UnityLogo", "UnityLogoLarge", "UnLinked", "UnLinked@2x", "UpArrow",
            "Update-Available", "Update-Available@2x", "UssScript Icon", "UxmlScript Icon", "Valid", "Valid@2x",
            "vcs_change", "vcs_document", "vcs_incoming",
            "VerticalLayoutGroup Icon", "VerticalSplit", "VideoClip Icon", "VideoClipImporter Icon", "VideoEffect Icon",
            "VideoPlayer Icon", "ViewToolMove On", "ViewToolMove On@2x", "ViewToolMove", "ViewToolMove@2x",
            "ViewToolOrbit On", "ViewToolOrbit On@2x", "ViewToolOrbit", "ViewToolOrbit@2x", "ViewToolZoom On",
            "ViewToolZoom On@2x", "ViewToolZoom", "ViewToolZoom@2x", "VisibilityOff", "VisibilityOn",
            "VisualEffect Gizmo", "VisualEffect Icon", "VisualEffectAsset Icon", "VisualEffectSubgraphBlock Icon",
            "VisualEffectSubgraphOperator Icon", "VisualTreeAsset Icon", "VUMeterTextureHorizontal",
            "VUMeterTextureVertical", "WaitSpin00", "WaitSpin01", "WaitSpin02", "WaitSpin03", "WaitSpin04",
            "WaitSpin05", "WaitSpin06", "WaitSpin07", "WaitSpin08", "WaitSpin09", "WaitSpin10", "WaitSpin11", "Warning",
            "Warning@2x", "WelcomeScreen.AssetStoreLogo", "WheelCollider Icon", "WheelJoint2D Icon", "winbtn_graph",
            "winbtn_graph_close_h", "winbtn_graph_max_h", "winbtn_graph_min_h", "winbtn_mac_close",
            "winbtn_mac_close@2x", "winbtn_mac_close_a", "winbtn_mac_close_a@2x", "winbtn_mac_close_h",
            "winbtn_mac_close_h@2x", "winbtn_mac_inact", "winbtn_mac_inact@2x", "winbtn_mac_max", "winbtn_mac_max@2x",
            "winbtn_mac_max_a", "winbtn_mac_max_a@2x", "winbtn_mac_max_h", "winbtn_mac_max_h@2x", "winbtn_mac_min",
            "winbtn_mac_min@2x", "winbtn_mac_min_a", "winbtn_mac_min_a@2x", "winbtn_mac_min_h", "winbtn_mac_min_h@2x",
            "winbtn_win_close", "winbtn_win_close@2x", "winbtn_win_close_a", "winbtn_win_close_a@2x",
            "winbtn_win_close_h", "winbtn_win_close_h@2x", "winbtn_win_max", "winbtn_win_max@2x", "winbtn_win_max_a",
            "winbtn_win_max_a@2x", "winbtn_win_max_h", "winbtn_win_max_h@2x", "winbtn_win_min", "winbtn_win_min_a",
            "winbtn_win_min_h", "winbtn_win_rest", "winbtn_win_restore", "winbtn_win_restore@2x",
            "winbtn_win_restore_a", "winbtn_win_restore_a@2x", "winbtn_win_restore_h", "winbtn_win_restore_h@2x",
            "winbtn_win_rest_a", "winbtn_win_rest_h", "WindZone Gizmo", "WindZone Icon",
            "WorldAnchor Icon",
            "_Help", "_Help@2x", "_Menu", "_Menu@2x", "_Popup", "_Popup@2x",
        };

        private static string inputFilterText = ""; //用户输入的过滤文本

        private static int xCount = 4; //一排几个
        private static Vector2 iconBtnMinSize = new Vector2(30, 70);
        private static Vector2 iconBtnMaxSize = new Vector2(70, 70);

        private static Vector2 scrollPos = Vector2.zero;

        protected override void DrawGuiContent()
        {
            DrawIconGallery();
        }

        private void DrawIconGallery()
        {
            GUILayout.BeginHorizontal();
            GUILayout.Label("Input filter text: ", GUILayout.ExpandWidth(false));
            inputFilterText = GUILayout.TextField(inputFilterText).Trim();
            GUILayout.EndHorizontal();

            string[] useNames = iconNames;

            //filter
            if (!string.IsNullOrWhiteSpace(inputFilterText))
                useNames = useNames.Where((name) => name.ToLower().Contains(inputFilterText.ToLower())).ToArray();

            scrollPos = GUILayout.BeginScrollView(scrollPos);

            xCount = (int)(PluginHubWindow.Window.position.width / iconBtnMaxSize.x);

            int lastStartRowIndex = -1;
            int iconCounter = 0;
            //绘制所有icon
            for (int i = 0; i < useNames.Length; i++)
            {
                if (PluginHubFunc.ShouldBeginHorizontal(i, xCount))
                {
                    GUILayout.BeginHorizontal();
                    lastStartRowIndex = i;
                }

                string text = useNames[i];

                //make shut up if icon not found 让控制台暂时安静闭嘴
                Debug.unityLogger.logEnabled = false; //unity 5.4 以上可以用这个api关闭输出
                GUIContent guiContent = EditorGUIUtility.IconContent(text);
                Debug.unityLogger.logEnabled = true;

                if (guiContent != null && guiContent.image != null)
                {
                    iconCounter++;
                    guiContent.text = "";
                    guiContent.tooltip = $"{text}({guiContent.image.width}x{guiContent.image.height})";

                    //icon 按钮
                    if (GUILayout.Button(guiContent,
                            GUILayout.Width(guiContent.image.width), GUILayout.Height(guiContent.image.height),
                            GUILayout.MaxWidth(iconBtnMaxSize.x), GUILayout.MaxHeight(iconBtnMaxSize.y),
                            GUILayout.MinWidth(iconBtnMinSize.x), GUILayout.MinHeight(iconBtnMinSize.y)))
                    {
                        EditorGUIUtility.systemCopyBuffer = text;
                        Debug.Log($"已拷贝：{text}，可以在代码中使用EditorGUIUtility.IconContent({text})创建带图标的GUIContent");
                    }
                }

                if (PluginHubFunc.ShouldEndHorizontal(i, xCount))
                {
                    GUILayout.EndHorizontal();
                    lastStartRowIndex = -1;
                }
            }

            if (lastStartRowIndex != -1)
                GUILayout.EndHorizontal();

            GUILayout.EndScrollView();
            GUILayout.Label($"Icon count : {iconCounter}");
        }
    }
}